New file parser. - (Update) Fixed issues with file encodings and added arguments for new file parser.

diff --git a/runPM b/runPM
--- a/runPM
+++ b/runPM
@@ -4,7 +4,7 @@
 #
 # Author: Daniel A Cuevas
 # Created on 22 Nov. 2013
-# Updated on 16 Mar. 2015
+# Updated on 18 Mar. 2015
 
 usage() {
     echo "
@@ -16,7 +16,7 @@ Required
    -c [config_filename]    : Configuration file listing all parameters (this takes precedence)
    OR
    -i [PM_data_directory]  : PM data directory path to files
-   -n [output_directory]   : Output directory (will create if non-existent)
+   -d [output_directory]   : Output directory (will create if non-existent)
    -o [output_name]        : Suffix appended to all output files
 
 Optional
@@ -24,7 +24,9 @@ Optional
    -f                      : Flag if filter should be applied to growth curves during PManalysis
    -h, -?, --help          : This help message
    -m                      : Generate figures
+   -n [number of plates]   : Number of plates [used with some parsers]
    -p [plate_filename]     : Plate filepath
+   -s [sample_filename]    : Sample name and replicate file [used with some parsers]
    -t [input_file_type]    : Format number of PM plate format. Range: [1, $1]
    -v                      : Verbose output
 
@@ -100,9 +102,10 @@ filterflag=""
 verboseFlag=""
 debugFlag=""
 imageFlag=""
-num_replicates=1
+numplates=1
 frmtype=1
-frmmax=2
+frmmax=3
+samplefile=""
 pythonexec="/usr/local/bin/python3.4"
 
 while [[ $# != 0 ]]; do
@@ -115,6 +118,11 @@ while [[ $# != 0 ]]; do
         shift
         [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing config filename" >&2 && usage && exit 2
         configfile=$1
+        ;;
+    -d)
+        shift
+        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -d value" >&2 && usage && exit 2
+        outputdir=$1
         ;;
     --debug)
         debugFlag="--debug"
@@ -133,7 +141,7 @@ while [[ $# != 0 ]]; do
     -n)
         shift
         [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -n value" >&2 && usage && exit 2
-        outputdir=$1
+        numplates=$1
         ;;
     -o)
         shift
@@ -144,6 +152,11 @@ while [[ $# != 0 ]]; do
         shift
         [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -p value" >&2 && usage && exit 2
         plate=$1
+        ;;
+    -s)
+        shift
+        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -s value" >&2 && usage && exit 2
+        samplefile=$1
         ;;
     -t)
         shift
@@ -184,11 +197,24 @@ checkOutputDir $outputdir
 # Check if script direectory exists
 checkScriptDir $pyscriptdir
 
+# Check for UTF-8 encodings
+getTime && echo "${currtime}    *****Checking character encodings*****" >&1
+for f in ${inputfile[@]}; do
+    enc=$(file --mime $inputfiledir/$f | grep -ic "utf-8")
+    if [[ $enc -eq 0 ]]; then
+        f=$(echo $f | perl -ne 's/([\(\)])/\\$1/g; print;') # Escape any parentheses in input file name
+        cmd="iconv -f utf16 -t utf8 $inputfiledir/$f > tmp.txt && mv tmp.txt $inputfiledir/$f"
+        [[ $verbose ]] && getTime && echo "${currtime}    Executing $cmd" >&1
+        eval $cmd
+        [[ $? -ne 0 ]] && getTime && error "${currtime}    Fail on command: $cmd"
+    fi
+done
+
 # Convert input files line endings from DOS to UNIX
 getTime && echo "${currtime}    *****Checking line endings*****" >&1
 for f in ${inputfile[@]}; do
     f=$(echo $f | perl -ne 's/([\(\)])/\\$1/g; print;') # Escape any parentheses in input file name
-    cmd="perl -i -npe 's/\r\n?/\n/g' $inputfiledir/$f"
+    cmd="perl -i -pe 's/\r\n?/\n/g' $inputfiledir/$f"
     [[ $verbose ]] && getTime && echo "${currtime}    Executing $cmd" >&1
     eval $cmd
     [[ $? -ne 0 ]] && getTime && error "${currtime}    Fail on command: $cmd"
@@ -201,6 +227,9 @@ case $frmtype in
         ;;
     2)
         p_script="well_vs_time_parser.pl"
+        ;;
+    3)
+        p_script="pmParser_v2.pl"
         ;;
     *)
         echo "Format type must be an integer within the range [1, $frmmax]." >&2
@@ -217,9 +246,9 @@ out="raw_curves_${outputname}.txt"
 
 # Check if plate was supplied
 if [[ $plate ]]; then
-    cmd="${plscriptdir}/${p_script} -d $inputfiledir -p $plate > $outputdir/${out}"
+    cmd="${plscriptdir}/${p_script} -d $inputfiledir -p $plate -n $numplates -s $samplefile > $outputdir/${out}"
 else
-    cmd="${plscriptdir}/${p_script} -d $inputfiledir > $outputdir/${out}"
+    cmd="${plscriptdir}/${p_script} -d $inputfiledir -n $numplates -s $samplefile > $outputdir/${out}"
 fi
 [[ $verbose ]] && getTime && echo "${currtime}    Executing $cmd" >&1
 eval $cmd
