Pipeline options. - (New) Added option to clear results directory before analysis. - (Update) Code cleanup.

diff --git a/runPM b/runPM
--- a/runPM
+++ b/runPM
@@ -4,10 +4,12 @@
 #
 # Author: Daniel A Cuevas
 # Created on 22 Nov 2013
-# Updated on 21 Aug 2015
+# Updated on 26 Aug 2015
 
-usage() {
-    echo "$2
+VERSION="1.3"
+
+printversion() {
+    echo "
         ___          _               _
        / _ \/\/\    /_\  _ __   __ _| |_   _ _______ _ __
       / /_)/    \  //_\\\| '_ \ / _\` | | | | |_  / _ \ '__|
@@ -15,8 +17,13 @@ usage() {
      \/   \/    \/\_/ \_/_| |_|\__,_|_|\__, /___\___|_|
                                         |___/
 
-PMAnalyzer version 1.2
+PMAnalyzer version $VERSION
+" >&1 | tee -a $log
+}
 
+
+usage() {
+    echo "$2
 usage: $scriptname -c config_filename [Options]
 OR
 usage: $scriptname -i PM_data_directory -d output_directory -o output_name [Options]
@@ -29,6 +36,7 @@ Required
    -o [output_name]        : Suffix appended to all output files
 
 Optional
+   --clear                 : Clear out results directory of old files.
    --debug                 : Print out debug messages
    -e [encoding]           : Check for file encoding of original data [Default: UTF-16]
    -f                      : Flag if filter should be applied to growth curves during PManalysis
@@ -139,14 +147,17 @@ while [[ $# != 0 ]]; do
         usage $frmmax
         exit 2
         ;;
+    --clear)
+        clearRes=0
+        ;;
     -c)
         shift
-        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing config filename" >&2 && usage && exit 2
+        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing config filename" >&2 && usage $frmmax && exit 2
         configfile=$1
         ;;
     -d)
         shift
-        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -d value" >&2 && usage && exit 2
+        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -d value" >&2 && usage $frmmax && exit 2
         outputdir=$1
         ;;
     --debug)
@@ -154,7 +165,7 @@ while [[ $# != 0 ]]; do
         ;;
     -e)
         shift
-        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -d value" >&2 && usage && exit 2
+        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -d value" >&2 && usage $frmmax && exit 2
         encoding=$1
         ;;
     -f)
@@ -165,7 +176,7 @@ while [[ $# != 0 ]]; do
         ;;
     -i)
         shift
-        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -i value" >&2 && usage && exit 2
+        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -i value" >&2 && usage $frmmax && exit 2
         inputfiledir=$1
         ;;
     -m)
@@ -173,27 +184,27 @@ while [[ $# != 0 ]]; do
         ;;
     -o)
         shift
-        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -o value" >&2 && usage && exit 2
+        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -o value" >&2 && usage $frmmax && exit 2
         outputname=$1
         ;;
     -p)
         shift
-        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -p value" >&2 && usage && exit 2
+        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -p value" >&2 && usage $frmmax && exit 2
         plate=$1
         ;;
     --python)
         shift
-        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing --python value" >&2 && usage && exit 2
+        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing --python value" >&2 && usage $frmmax && exit 2
         pythonexec=$1
         ;;
     -s)
         shift
-        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -s value" >&2 && usage && exit 2
+        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -s value" >&2 && usage $frmmax && exit 2
         samplefile=$1
         ;;
     -t)
         shift
-        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -t value" >&2 && usage && exit 2
+        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -t value" >&2 && usage $frmmax && exit 2
         frmtype=$1
         ;;
     -v)
@@ -238,7 +249,16 @@ log="${outputdir}/PMAnalyzer_out_${timestamp}.txt"
 
 # Remove leading slashes from output directory
 checkOutputDir $outputdir
-log="${outputdir}/PMAnalyzer_out_${timestamp}.txt"
+
+# Print version header
+printversion
+
+# Check to empty out results folder
+if [[ $clearRes ]]; then
+    getTime
+    echo "${currtime}    Clearing results folder"  >&1 | tee -a $log
+    rm $outputdir/*
+fi
 
 # Check if input file or directory exists
 checkInputDirectory $inputfiledir
@@ -257,6 +277,8 @@ for f in ${inputfile[@]}; do
         [[ $verbose ]] && getTime && echo "${currtime}    Executing $cmd"  >&1 | tee -a $log
         eval $cmd  2>&1 | tee -a $log
         [[ $? -ne 0 ]] && getTime && error "${currtime}    Fail on command: $cmd"
+    else
+        getTime && echo "${currtime}    OK!" >&1 | tee -a $log
     fi
 done
 
