Input file encoding. - (Update) Fix encoding identification.

diff --git a/runPM b/runPM
--- a/runPM
+++ b/runPM
@@ -4,7 +4,7 @@
 #
 # Author: Daniel A Cuevas
 # Created on 22 Nov. 2013
-# Updated on 24 Mar. 2015
+# Updated on 02 Apr. 2015
 
 usage() {
     echo "$2
@@ -22,6 +22,7 @@ Required
 
 Optional
    --debug                 : Print out debug messages
+   -e [encoding]           : Check for file encoding of original data [Default: UTF-16]
    -f                      : Flag if filter should be applied to growth curves during PManalysis
    -h, -?, --help          : This help message
    -m                      : Generate figures
@@ -64,6 +65,7 @@ checkInputDirectory() {
     fi
     # Store directory in new variable and remove trailing slash
     inputfiledir=$(echo $inputfiledir | perl -ne 'chomp; s/\/$//; print;')
+
     inputfile=$(ls $1)
 }
 
@@ -107,6 +109,7 @@ numplates=""
 frmtype=1
 frmmax=3
 samplefile=""
+encoding="UTF-16"
 pythonexec="/usr/local/bin/python3.4"
 
 while [[ $# != 0 ]]; do
@@ -127,6 +130,11 @@ while [[ $# != 0 ]]; do
         ;;
     --debug)
         debugFlag="--debug"
+        ;;
+    -e)
+        shift
+        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -d value" >&2 && usage && exit 2
+        encoding=$1
         ;;
     -f)
         filterflag="-f"
@@ -195,6 +203,11 @@ if [[ $frmtype -eq 3 ]] &&
     exit 2
 fi
 
+
+# Set internal field separator for files with spaces
+SAVEIFS=$IFS
+IFS=$(echo -en '\n\b')
+
 # Check if input file or directory exists
 checkInputDirectory $inputfiledir
 
@@ -207,10 +220,10 @@ checkScriptDir $pyscriptdir
 # Check for UTF-8 encodings
 getTime && echo "${currtime}    *****Checking character encodings*****" >&1
 for f in ${inputfile[@]}; do
-    enc=$(file --mime $inputfiledir/$f | egrep -ic "utf-8|us-ascii")
+    enc=$(file --mime "$inputfiledir/$f" | egrep -ic "utf-8|us-ascii")
     if [[ $enc -eq 0 ]]; then
-        f=$(echo $f | perl -ne 's/([\(\)])/\\$1/g; print;') # Escape any parentheses in input file name
-        cmd="iconv -f utf16 -t utf8 $inputfiledir/$f > tmp.txt && mv tmp.txt $inputfiledir/$f"
+        f=$(echo "$f" | perl -ne 's/([\(\)])/\\$1/g; print;') # Escape any parentheses in input file name
+        cmd="iconv -f $encoding -t UTF-8 \"$inputfiledir/$f\" > tmp.txt && mv tmp.txt \"$inputfiledir/$f\""
         [[ $verbose ]] && getTime && echo "${currtime}    Executing $cmd" >&1
         eval $cmd
         [[ $? -ne 0 ]] && getTime && error "${currtime}    Fail on command: $cmd"
@@ -220,8 +233,8 @@ done
 # Convert input files line endings from DOS to UNIX
 getTime && echo "${currtime}    *****Checking line endings*****" >&1
 for f in ${inputfile[@]}; do
-    f=$(echo $f | perl -ne 's/([\(\)])/\\$1/g; print;') # Escape any parentheses in input file name
-    cmd="perl -i -pe 's/\r\n?/\n/g' $inputfiledir/$f"
+    f=$(echo "$f" | perl -ne 's/([\(\)])/\\$1/g; print;') # Escape any parentheses in input file name
+    cmd="perl -i -pe 's/\r\n?/\n/g' \"$inputfiledir/$f\""
     [[ $verbose ]] && getTime && echo "${currtime}    Executing $cmd" >&1
     eval $cmd
     [[ $? -ne 0 ]] && getTime && error "${currtime}    Fail on command: $cmd"
@@ -236,7 +249,7 @@ case $frmtype in
         p_script="well_vs_time_parser.pl"
         ;;
     3)
-        p_script="pmParser_v2.pl -n $numplates -s $samplefile"
+        p_script="pmParser_v2.pl -n $numplates -s \"$samplefile\""
         ;;
     *)
         echo "Format type must be an integer within the range [1, $frmmax]." >&2
@@ -276,4 +289,6 @@ getTime && echo "${currtime}    *****Starting modeling script*****" >&1
 eval $cmd
 [[ $? -ne 0 ]] && getTime && error "${currtime}    Fail on command: $cmd"
 
+# Restore internal field separator
+IFS=$SAVEIFS
 getTime && echo "${currtime}    *****Completed!*****" >&1
