Growth classification heatmap. - (New) Implementing new heatmap into pipeline.

diff --git a/runPM b/runPM
--- a/runPM
+++ b/runPM
@@ -413,6 +413,14 @@ if [ -n "$imageFlag" ]; then
     [[ $verbose ]] && getTime && echo "${currtime}    Executing $cmd"  >&1 | tee -a $log
     eval $cmd  2>&1 | tee -a $log
     [[ $? -ne 0 ]] && getTime && error "${currtime}    Fail on command: $cmd"
+
+    getTime && echo "${currtime}    Generating growth classification heatmap"  >&1 | tee -a $log
+    in="${outputdir}/logistic_params_mean_${outputname}.txt"
+    out="${outputdir}/growthclass"
+    cmd="Rscript ${rscriptdir}/growthClassHeatmap.R -i $in -o $out -f png $pflag"
+    [[ $verbose ]] && getTime && echo "${currtime}    Executing $cmd"  >&1 | tee -a $log
+    eval $cmd  2>&1 | tee -a $log
+    [[ $? -ne 0 ]] && getTime && error "${currtime}    Fail on command: $cmd"
 else
     getTime && echo "${currtime}    *****Figures flag not given*****"  >&1 | tee -a $log
 fi
