runPM - Spacing fixes and small bug fixes.

diff --git a/runPM b/runPM
--- a/runPM
+++ b/runPM
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 usage() {
-	echo "
+    echo "
 usage: $scriptname -c config_filename [Options]
 OR
 usage: $scriptname -i PM_data_directory -n output_directory -o output_name -p plate_filename -r \"regex\" [Options]
@@ -21,23 +21,25 @@ Optional
    -f                      : Flag if filter should be applied to growth curves during PManalysis
    -h, -?, --help          : This help message
    --hm                    : Use new harmonic mean calculation
-   --reps                  : Flag if there are replicates involved
+   --num_replicates        : Flag if there are replicates involved
    -v                      : Verbose output
 
 " >&2
 }
 
 error() {
-	echo "*****FATAL ERROR OCCURRED*****" >&1
-	echo $1 >&2
-	exit 1
+    echo "*****FATAL ERROR OCCURRED*****" >&1
+    echo $1 >&2
+    exit 1
 }
 
 checkConfigFile() {
     configfile_secured="/tmp/PMAnalyzer_secured.cfg"
     if egrep -q -v '^#|^[^ ]*=[^;]*' "$1"; then
+        getTime && echo "${currtime}    Config file is improper. Attempting to clean..." >&2
         # filter the original to a new file
         egrep '^#|^[^ ]*=[^;&]*'  "$configfile" > "$configfile_secured"
+        getTime && echo "${currtime}    Cleaned config file @ ${configfile_secured}" >&2
         configfile="$configfile_secured"
     fi
     source "$configfile"
@@ -45,7 +47,7 @@ checkConfigFile() {
 
 checkInputDirectory() {
     if [[ ! -d $1 ]]; then
-        getTime && error "${currtime}	Directory '$1' does not exist."
+        getTime && error "${currtime}    Directory '$1' does not exist."
     fi
     # Store directory in new variable and remove trailing slash
     inputfiledir=$(echo $inputfiledir | perl -ne 'chomp; s/\/$//; print;')
@@ -53,27 +55,27 @@ checkInputDirectory() {
 }
 
 checkOutputDir() {
-	# Remove trailing slash
-	outputdir=$(echo $1 | perl -ne 'chomp; s/\/$//; print;')
-	# Check to see if directory needs to be created
-	[[ ! -d $1 ]] && getTime && echo "${currtime}	Output directory '$1' does not exist. Creating now." >&1 && mkdir $1
+    # Remove trailing slash
+    outputdir=$(echo $1 | perl -ne 'chomp; s/\/$//; print;')
+    # Check to see if directory needs to be created
+    [[ ! -d $1 ]] && getTime && echo "${currtime}    Output directory '$1' does not exist. Creating now." >&1 && mkdir $1
 }
 
 
 checkScriptDir() {
-	if [[ -z $1 ]]; then
-		pyscriptdir="./" # Script directory is current directory
-	else
-		[[ ! -d $1 ]] && getTime && error "${currtime}	Script directory '$1' does not exist."
-		pyscriptdir=$1
-	fi
-	# Remove trailing slash
-	pyscriptdir=$(echo $pyscriptdir | perl -ne 'chomp; s/\/$//; print;')
+    if [[ -z $1 ]]; then
+        pyscriptdir="./" # Script directory is current directory
+    else
+        [[ ! -d $1 ]] && getTime && error "${currtime}    Script directory '$1' does not exist."
+        pyscriptdir=$1
+    fi
+    # Remove trailing slash
+    pyscriptdir=$(echo $pyscriptdir | perl -ne 'chomp; s/\/$//; print;')
 }
 
 
 getTime() {
-	currtime=$(date "+[%F %H:%M:%S]")
+    currtime=$(date "+[%F %H:%M:%S]")
 }
 
 ####################################################
@@ -88,69 +90,69 @@ filterflag=""
 hmFlag=""
 verboseFlag=""
 debugFlag=""
-reps=1
+num_replicates=1
 
 while [[ $# != 0 ]]; do
-	case $1 in
-	-h|-\?|--help)
-		usage
-		exit 2
-		;;
-	-c)
+    case $1 in
+    -h|-\?|--help)
+        usage
+        exit 2
+        ;;
+    -c)
         shift
-		[[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing config filename" >&2 && usage && exit 2
-		configfile=$1
-		;;
-	--clear)
-		clearfiles=0
-		;;
-	--debug)
-		debugFlag="--debug"
-		;;
-	-f)
+        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing config filename" >&2 && usage && exit 2
+        configfile=$1
+        ;;
+    --clear)
+        clearfiles=0
+        ;;
+    --debug)
+        debugFlag="--debug"
+        ;;
+    -f)
         filterflag="-f"
-		;;
+        ;;
     --hm)
         hmFlag="-g"
         ;;
-	-i)
-		shift
-		[[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -i value" >&2 && usage && exit 2
-		inputfiledir=$1
-		;;
-	-n)
-		shift
-		[[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -n value" >&2 && usage && exit 2
-		outputdir=$1
-		;;
-	-o)
-		shift
-		[[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -o value" >&2 && usage && exit 2
-		outputname=$1
-		;;
-	-p)
-		shift
-		[[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -p value" >&2 && usage && exit 2
-		plate=$1
-		;;
-	-r)
-		shift
-		[[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -r value" >&2 && usage && exit 2
-		regex=$1
-		;;
-	--reps)
-		reps=2
-		;;
-	-v)
-		verbose=0;
+    -i)
+        shift
+        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -i value" >&2 && usage && exit 2
+        inputfiledir=$1
+        ;;
+    -n)
+        shift
+        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -n value" >&2 && usage && exit 2
+        outputdir=$1
+        ;;
+    -o)
+        shift
+        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -o value" >&2 && usage && exit 2
+        outputname=$1
+        ;;
+    -p)
+        shift
+        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -p value" >&2 && usage && exit 2
+        plate=$1
+        ;;
+    -r)
+        shift
+        [[ ! $1 || $(printf "%s" "$1" | perl -ne 'm/(^-.$)/; print $1;') ]] && echo "Missing -r value" >&2 && usage && exit 2
+        regex=$1
+        ;;
+    --num_replicates)
+        num_replicates=2
+        ;;
+    -v)
+        verbose=0;
         verboseFlag="-v"
-		;;
-	*)
-		echo "Unknown option $1" >&2
-		usage
-		exit 2
-	esac
-	shift
+        ;;
+    *)
+        echo "Unknown option $1" >&2
+        usage
+        exit 2
+    esac
+    shift
 done
 
 # Check if config file was supplied
@@ -160,12 +162,12 @@ fi
 
 # Check if required variables are set
 if [[ ! $inputfiledir ||
-	! $outputname ||
-	! $plate ||
-	! $outputdir ||
-	! $regex ]]; then
-	usage
-	exit 2
+    ! $outputname ||
+    ! $plate ||
+    ! $outputdir ||
+    ! $regex ]]; then
+    usage
+    exit 2
 fi
 
 # Check if input file or directory exists
@@ -178,13 +180,13 @@ checkOutputDir $outputdir
 checkScriptDir $pyscriptdir
 
 # Convert input files line endings from DOS to UNIX
-getTime && echo "${currtime}	*****Checking line endings*****" >&1
+getTime && echo "${currtime}    *****Checking line endings*****" >&1
 for f in ${inputfile[@]}; do
-	f=$(echo $f | perl -ne 's/([\(\)])/\\$1/g; print;') # Escape any parentheses in input file name
-	cmd="dos2unix.sh $inputfiledir/$f"
-	[[ $verbose ]] && getTime && echo "${currtime}	Executing $cmd" >&1
-	eval $cmd
-	[[ $? -ne 0 ]] && getTime && error "${currtime}	Fail on command: $cmd"
+    f=$(echo $f | perl -ne 's/([\(\)])/\\$1/g; print;') # Escape any parentheses in input file name
+    cmd="perl -i -npe 's/\r\n?/\n/g' $inputfiledir/$f"
+    [[ $verbose ]] && getTime && echo "${currtime}    Executing $cmd" >&1
+    eval $cmd
+    [[ $? -ne 0 ]] && getTime && error "${currtime}    Fail on command: $cmd"
 done
 
 ################################################
@@ -194,16 +196,16 @@ done
 parsedfiles=() # Will contain array of file names for next step
 
 # Iterate through files and produce first parsed version of each file
-getTime && echo "${currtime}	*****Parsing phase 1*****" >&1
+getTime && echo "${currtime}    *****Parsing phase 1*****" >&1
 for f in ${inputfile[@]}; do
-	rname=$(echo "$f,$regex" | perl -ne 'chomp; ($f,$r)=split /,/; $f=~m/($r)/; print $1;')
-	f=$(echo $f | perl -ne 's/([\(\)])/\\$1/g; print;') # Escape any parentheses in input file name
-	out="${rname}_${outputname}.txt"
-	parsedfiles=("${parsedfiles[@]}" "$outputdir/$out") # Append to array
-	cmd="${plscriptdir}/biologout_parse2 $inputfiledir/$f > $outputdir/${out}"
-	[[ $verbose ]] && getTime && echo "${currtime}	Executing $cmd" >&1
-	eval $cmd
-	[[ $? -ne 0 ]] && getTime && error "${currtime}	Fail on command: $cmd"
+    rname=$(echo "$f,$regex" | perl -ne 'chomp; ($f,$r)=split /,/; $f=~m/($r)/; print $1;')
+    f=$(echo $f | perl -ne 's/([\(\)])/\\$1/g; print;') # Escape any parentheses in input file name
+    out="${rname}_${outputname}.txt"
+    parsedfiles=("${parsedfiles[@]}" "$outputdir/$out") # Append to array
+    cmd="${plscriptdir}/biologout_parse2 $inputfiledir/$f > $outputdir/${out}"
+    [[ $verbose ]] && getTime && echo "${currtime}    Executing $cmd" >&1
+    eval $cmd
+    [[ $? -ne 0 ]] && getTime && error "${currtime}    Fail on command: $cmd"
 done
 
 
@@ -212,11 +214,11 @@ done
 ################################################
 
 out="${outputname}_data.txt"
-cmd="${plscriptdir}/pm_data_organizer4 -p $plate -f ${parsedfiles[@]} -r $reps > $outputdir/${out}"
-getTime && echo "${currtime}	*****Parsing phase 2*****" >&1
-[[ $verbose ]] && getTime && echo "${currtime}	Executing $cmd" >&1
+cmd="${plscriptdir}/pm_data_organizer4 -p $plate -f ${parsedfiles[@]} -r $num_replicates > $outputdir/${out}"
+getTime && echo "${currtime}    *****Parsing phase 2*****" >&1
+[[ $verbose ]] && getTime && echo "${currtime}    Executing $cmd" >&1
 eval $cmd
-[[ $? -ne 0 ]] && getTime && error "${currtime}	Fail on command: $cmd"
+[[ $? -ne 0 ]] && getTime && error "${currtime}    Fail on command: $cmd"
 
 
 ################################################
@@ -225,11 +227,11 @@ eval $cmd
 
 in="$outputdir/${out}"
 cmd="python ${pyscriptdir}/pmanalysis.py $in $outputdir -o $outputname $filterflag $hmFlag $verboseFlag $debugFlag"
-getTime && echo "${currtime}	*****Starting modeling script*****" >&1
-[[ $verbose ]] && getTime && echo "${currtime}	Executing $cmd" >&1
+getTime && echo "${currtime}    *****Starting modeling script*****" >&1
+[[ $verbose ]] && getTime && echo "${currtime}    Executing $cmd" >&1
 eval $cmd
-[[ $? -ne 0 ]] && getTime && error "${currtime}	Fail on command: $cmd"
+[[ $? -ne 0 ]] && getTime && error "${currtime}    Fail on command: $cmd"
 
-getTime && echo "${currtime}	*****Completed!*****" >&1
+getTime && echo "${currtime}    *****Completed!*****" >&1
 
 [[ $clearfiles ]] && rm ${parsedfiles[@]}
